### ISSUE TITLE
Changing database.yml default values

### ISSUE THREAD

**Issue by epintos** [capistrano-plugins/capistrano-postgresql#18]
Hello,

I'm trying to setup a web application in [Amazon EC2](http://aws.amazon.com/es/ec2/) with [Amazon RDS](http://aws.amazon.com/es/rds/).

My `config/deploy/staging.rb`looks something like this:

```ruby
role :app, %w(user@ec2_server_ip)
role :web, %w(user@ec2_server_ip)
role :db,  %w(user@ec2_server_ip)

set :pg_database, :db_name
set :pg_user, :db_user
set :pg_password, :db_password
set :pg_host, 'rds_server_ip'
```

From what I understand from the `README`, this should replace the defaults values from the `database.yml`file when I run the capistrano postgresql tasks, but this is not happening. Am I missing something?

**Comment by bruno-** [comment]
Hey, sorry for not responding earlier to this..  Hopefully you've solved this by now, but just in case here's the answer.

You're using real strings for the database, user and password options right?

I think this is a no-go:
```ruby
set :pg_database, :db_name
set :pg_user, :db_user
set :pg_password, :db_password
```

If you do \*not* need to change these options, just omit them and the defaults will be used. If you \*do* want to change these options, then using strings for values is probably a better choice, like you did with `pg_host` option:

```ruby
set :pg_host, 'rds_server_ip'
```

As for updating the `database.yml` file on the server: if the file already exists, there's no "automatic" way to overwrite it. Reason for this is, we're very careful and do not want to risk overriding or loosing the password field (which is likely random generated, not set by the user).

@epintos, for your case, the easiest thing would be to log into the server and manually change `hostname` field in `#{deploy_path}/db/database.yml` and `#{deploy_path}/shared/config/database.yml`.

The next time the application is restarted (or redeployed) it should use new values from `database.yml`.

Hope that helps! Since we have quite some open issues/questions with `capistrano-plugins` org, I'll close this one. Please feel free to reopen if you have more troubles or questions.

**Comment by epintos** [comment]
@bruno- Thanks for the reply. I did exactly what you say about changing it manually in the server and it worked, the issue with this is that someone can override it and I will lose it.

**Comment by bruno-** [comment]
Hey, good to hear you got this working!

As for the issue with someone manually overriding the `database.yml` file.. well, hopefully the people that have access to the server know what they are doing. If this still worries you though, I think this plugin can't do much about it. Maybe you should consider backing up important credentials or such in case a bad thing happens.

In any case, I hope things stay online for you :wink:
