### ISSUE TITLE
Incorrect Password in database.yml

### ISSUE THREAD

**Issue by tomprats** [capistrano-plugins/capistrano-postgresql#47]
Due to PR #37, I'm getting

> PG::ConnectionBad: FATAL:  password authentication failed for user "tom_production"
> FATAL:  password authentication failed for user "tom_production"

Since `pg_password` is randomly generated when running my `cap production setup`, the only reference to it is in the `db/database.yml` file. That file is getting deleted in `postgresql:remove_yml_files` and a new one is generated with a new randomly generated password that's incorrect.

I'm willing to try and make a PR to fix the problem, but I'm unsure of what direction to go in. Before it removes the yml file, should it grab the config values that aren't manually set? Or should it merge yml files instead of removing existing ones?

Let me know what you think! Thanks,
Tom

**Comment by NorseGaud** [comment]
Hey dude, thanks for letting me know. Want to be sure I can replicate it. What does, removing any sensitive info of course, your config/deploy/(environment).rb file look like?

At first glance we can't have both the ability for users to change the pool size and also the ability to initially generate the random password. With that said, it is possible to solve this by generating the archetype file line by line (instead of using a template) and then any subsequent cap setup requests would check each line to see if it changed or not, skipping the password line. Way better solution if we want to support everything we do from here on out. 

Anything you can provide so I can replicate your setup, I'd appreciate.

**Comment by tomprats** [comment]
Right now these are the privileges for my users as I work on debugging potential problems:
User - deploy - sudo
PG User - deploy - superuser

```
# Combined deploy.rb and deploy/production.rb

lock "~> 3.10.1"

server "shared.tomify.me", user: "deploy", roles: [:app, :db, :web], primary: true
after "deploy:restart", "deploy:cleanup"

set :application, "my-website"
set :keep_releases, 3
set :repo_url, "git@github.com:tomprats/my-website.git"
set :keep_assets, 3
append :linked_dirs, "log", "tmp/pids", "tmp/cache", "tmp/sockets", "vendor/bundle", "public/system", "public/uploads"
set :migration_role, :app

set :init_system, :systemd
set :nginx_server_name, "www.my-website.com"
set :pg_system_user, "deploy"
set :pg_without_sudo, true
set :system_user, "deploy"
```

I just started using Capistrano but am very interested in playing around in it, so let me know any ways I can help. I might try to create a new app with the minimal setup to test things out on, but I think we already know what the problem is.

Here are some questions towards the potential line by line version of the archetype file. I'd love to try and tackle a PR for it or test it out for you:
1. Would it need to be backwards compatible?
2. Should it modify the current rake tasks? Or use completely new ones so it's fully opt-in?
3. What kind of config options do you see for it?

**Comment by NorseGaud** [comment]
Hey Tom, I've added the code and tested all situations I could think of (except for the pull request you put in yesterday; still need to test it). Here is the pull request: https://github.com/capistrano-plugins/capistrano-postgresql/pull/48

Jump into the branch and download the source. Manually install the gem for me and check if it fixes your problem. Testing is always a big help.

> Would it need to be backwards compatible?
Not necessarily, especially with the change to :pg_ask_for_password. I version bumped from 4.7.0 to 4.8.0 so people know when they upgrade their gem that there is significant code changes.

> Should it modify the current rake tasks? Or use completely new ones so it's fully opt-in?
I'm modifying existing rake tasks. The less methods and tasks we have defined, the better.

> What kind of config options do you see for it?
We're keeping existing configs of course, with a few changes to how :pg_ask_for_password and :pg_password take precedence over one-another. Adding more stuff is never suggested if you can help it. I added the rest of the available options for the activerecord/rails database.yml file because they should have been included initially. Now people can control, for example, timeout seconds in the deploy/(environment).rb file.

**Comment by NorseGaud** [comment]
Tested your pull request in mine for the other problems. Seems to work just fine. Perfect time to remove :system_user anyway. Please test and comment on the pull request when you get a chance.
