### ISSUE TITLE
Problem with `pg_generate_random_password`

### ISSUE THREAD

**Issue by tomprats** [capistrano-plugins/capistrano-postgresql#57]
The readme warns about it a little but I don't think the potential consequences are clear (or worth it).  The problem is that an app won't be able to reach its database from the time `cap setup` is run until `cap deploy` finishes. The most common scenario that causes it is when you add a new capistrano gem.

For example, I recently added sidekiq to one of my apps. Since most gems recommend you run `cap setup` when you add them, it meant my website lost connection to the DB until I also ran `cap deploy`.

Honestly, I think it might be a good idea to remove the `pg_generate_random_password` option. I was trying to look at the code to see if there was a way around changing the password on every setup, but I couldn't find a way

**Comment by NorseGaud** [comment]
Good catch! I’m not against removing it, but it’d be cool to find a way to solve the problem in the setup process instead. Might have to redesign some of the ordering that happens. If you figure it out before I do, please do a PR. Otherwise, it might be a while until I can fix it. I started a new job and have to put my full time into it for a few months.

**Comment by tomprats** [comment]
Looks like you added some comments in to make things more clear, I'd say this is solved!
